language: c

env:
  global:
    - MAKEFLAGS="-j2"
    - DECODE_ARINC=./src/examples/decode_arinc
    - SAMPLE_ADSC="d /BOMASAI.ADS.VT-ANB072501A070A988CA73248F0E5DC10200000F5EE1ABC000102B885E0A19F5"
    - SAMPLE_CPDLC="d /AKLCDYA.AT1.B-2727A0D5470C3D803BA464FAE2A15530DA2448312641AB425383320C74009CE009090A2CCA506AA61941DCA5005763"

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

script:
  - mkdir build
  - cd build
  - cmake ../
  - make VERBOSE=1
  - sudo make install
  - ${DECODE_ARINC} ${SAMPLE_ADSC}
  - '${DECODE_ARINC} ${SAMPLE_ADSC} | grep -q "Temperature: -62.75 C"'
  - ${DECODE_ARINC} ${SAMPLE_CPDLC}
  - '${DECODE_ARINC} ${SAMPLE_CPDLC} | grep -q "Flight level: 360"'
